import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/components/authProvider";
import { Toaster } from "@/components/ui/toaster";
import "./prosemirror.css";
import EditorProvider from "./provider";
import { Poppins } from "next/font/google";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({
  subsets: ["latin"], // Optional subsets
  weight: ["400", "700"], // Specify weights as needed
  style: ["normal", "italic"], // Specify styles if needed
  display: "swap", // Improves font loading performance
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  antialiased`}>
        <AuthProvider>
          <EditorProvider>{children}</EditorProvider>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
